### ISSUE TITLE
Error - Could not pass event PlayerMoveEven

### ISSUE THREAD

**Issue by KaptenZee** [pmme/Boost#7]
[23:15:41 ERROR]: Could not pass event PlayerMoveEvent to Boost v1.19.3
java.lang.IllegalArgumentException: location
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1282) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1228) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at org.bukkit.entity.Entity.teleport(Entity.java:157) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.teleport(CraftPlayer.java:1223) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftEntity.teleport(CraftEntity.java:545) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at nz.pmme.Boost.Game.Game.setPlayerLost(Game.java:232) ~[Boost-1.19.3.jar:?]
        at nz.pmme.Boost.EventsListener.onPlayerMove(EventsListener.java:370) ~[Boost-1.19.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor648.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1832]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Rot.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1832]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by pmme** [comment]
Boost is attempting to teleport the losing player to the `game_loss:` location defined for the game arena in which they were playing. 
Your purpur server is rejecting the `location` value that is defined.

Please link your config.yml and let me know which game arena the player was playing in.

**Comment by pmme** [comment]
Closing as I'm guessing from my reply you fixed an incorrect location specified in your config.yml
